//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMM2.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSMM2.Resource.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Round に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNextRound {
            get {
                return ResourceManager.GetString("ButtonNextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonShuffle {
            get {
                return ResourceManager.GetString("ButtonShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List up player names. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionEntrySheet {
            get {
                return ResourceManager.GetString("DescriptionEntrySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single match rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionSingleMatch {
            get {
                return ResourceManager.GetString("DescriptionSingleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 on 3 match rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionThreeOnThreeMatch {
            get {
                return ResourceManager.GetString("DescriptionThreeOnThreeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Three Game match rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionTreeGameMatch {
            get {
                return ResourceManager.GetString("DescriptionTreeGameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemPlayerModeEntrySheet {
            get {
                return ResourceManager.GetString("ItemPlayerModeEntrySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemPlayerModeNumber {
            get {
                return ResourceManager.GetString("ItemPlayerModeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemPlayerModeRestart {
            get {
                return ResourceManager.GetString("ItemPlayerModeRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemResultDraw {
            get {
                return ResourceManager.GetString("ItemResultDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemResultLose {
            get {
                return ResourceManager.GetString("ItemResultLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemResultProgress {
            get {
                return ResourceManager.GetString("ItemResultProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemResultWin {
            get {
                return ResourceManager.GetString("ItemResultWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemRuleSingleMatch {
            get {
                return ResourceManager.GetString("ItemRuleSingleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Three Game Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemRuleThreeGameMatch {
            get {
                return ResourceManager.GetString("ItemRuleThreeGameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 on 3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemRuleThreeOnThreeMatch {
            get {
                return ResourceManager.GetString("ItemRuleThreeOnThreeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1st Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label1stMatch {
            get {
                return ResourceManager.GetString("Label1stMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2nd Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label2ndMatch {
            get {
                return ResourceManager.GetString("Label2ndMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3rd Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label3rdMatch {
            get {
                return ResourceManager.GetString("Label3rdMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BS Match Maker 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelAppTitle {
            get {
                return ResourceManager.GetString("LabelAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelAutoSave {
            get {
                return ResourceManager.GetString("LabelAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelCulture {
            get {
                return ResourceManager.GetString("LabelCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDrop {
            get {
                return ResourceManager.GetString("LabelDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MailAddress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelMailAddress {
            get {
                return ResourceManager.GetString("LabelMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelMatchLog {
            get {
                return ResourceManager.GetString("LabelMatchLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum Condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelMinimumCondition {
            get {
                return ResourceManager.GetString("LabelMinimumCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   As Current Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNewGameAsCurrentGame {
            get {
                return ResourceManager.GetString("LabelNewGameAsCurrentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Life Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNewGameEnableLifePoint {
            get {
                return ResourceManager.GetString("LabelNewGameEnableLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNewGameEntrySheet {
            get {
                return ResourceManager.GetString("LabelNewGameEntrySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNewGameNumberOfPlayer {
            get {
                return ResourceManager.GetString("LabelNewGameNumberOfPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNewGamePlayerEntryMode {
            get {
                return ResourceManager.GetString("LabelNewGamePlayerEntryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefix に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNewGamePlayerPrefix {
            get {
                return ResourceManager.GetString("LabelNewGamePlayerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNewGameRule {
            get {
                return ResourceManager.GetString("LabelNewGameRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNewGameTitle {
            get {
                return ResourceManager.GetString("LabelNewGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accept bye match duplication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRuleAcceptByeMatchDuplication {
            get {
                return ResourceManager.GetString("LabelRuleAcceptByeMatchDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accept gap match duplication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRuleAcceptGapMatchDuplication {
            get {
                return ResourceManager.GetString("LabelRuleAcceptGapMatchDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rule Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRuleSetting {
            get {
                return ResourceManager.GetString("LabelRuleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Life point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelUseLifePoint {
            get {
                return ResourceManager.GetString("LabelUseLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Opponent life pont に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelUseOpponentLifePoint {
            get {
                return ResourceManager.GetString("LabelUseOpponentLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Opponent match point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelUseOpponentMatchPoint {
            get {
                return ResourceManager.GetString("LabelUseOpponentMatchPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Opponent win point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelUseOpponentWinPoint {
            get {
                return ResourceManager.GetString("LabelUseOpponentWinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Win point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelUseWinPoint {
            get {
                return ResourceManager.GetString("LabelUseWinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAddPlayer {
            get {
                return ResourceManager.GetString("MenuAddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuClear {
            get {
                return ResourceManager.GetString("MenuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDeleteGame {
            get {
                return ResourceManager.GetString("MenuDeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuJson {
            get {
                return ResourceManager.GetString("MenuJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuNewGame {
            get {
                return ResourceManager.GetString("MenuNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRoundLog {
            get {
                return ResourceManager.GetString("MenuRoundLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelectGame {
            get {
                return ResourceManager.GetString("MenuSelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSendMail {
            get {
                return ResourceManager.GetString("MenuSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSetting {
            get {
                return ResourceManager.GetString("MenuSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSettingRule {
            get {
                return ResourceManager.GetString("MenuSettingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrefixGame {
            get {
                return ResourceManager.GetString("PrefixGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrefixRound {
            get {
                return ResourceManager.GetString("PrefixRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabPlayer {
            get {
                return ResourceManager.GetString("TabPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabRound {
            get {
                return ResourceManager.GetString("TabRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1st player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text1stPlayer {
            get {
                return ResourceManager.GetString("Text1stPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2nd Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text2ndPlayer {
            get {
                return ResourceManager.GetString("Text2ndPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3rd Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text3rdPlayer {
            get {
                return ResourceManager.GetString("Text3rdPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextAlert {
            get {
                return ResourceManager.GetString("TextAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BYE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBYE {
            get {
                return ResourceManager.GetString("TextBYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to make match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextFailToMakeMatch {
            get {
                return ResourceManager.GetString("TextFailToMakeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Give up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextGiveUp {
            get {
                return ResourceManager.GetString("TextGiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to rule setting. You may modify rule setting before retry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextGoToRuleSetting {
            get {
                return ResourceManager.GetString("TextGoToRuleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Life Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLifePoint {
            get {
                return ResourceManager.GetString("TextLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextMatchPoint {
            get {
                return ResourceManager.GetString("TextMatchPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opponent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextOpponent {
            get {
                return ResourceManager.GetString("TextOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextPlayer {
            get {
                return ResourceManager.GetString("TextPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pnayer Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextPlayerName {
            get {
                return ResourceManager.GetString("TextPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextResult {
            get {
                return ResourceManager.GetString("TextResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextWinPoint {
            get {
                return ResourceManager.GetString("TextWinPoint", resourceCulture);
            }
        }
    }
}
